### ISSUE TITLE
[Bug] Laggy Live interface when LES is on

### ISSUE THREAD

**Issue by OttoVonBorux** [LiveEnhancementSuite/LESforMacOS#20] opened 2023-03-05 17:10 UTC
**Describe the bug**
On Ventura 13.2.1 / Ableton Live 11.2.10

When LES is on, the whole Live interface becomes slightly laggy, sometimes upon clicking on another app then going back to Live, sometimes not the first time, sometimes it takes a little more time to become laggy (usually after an Onyx cleanup), sometimes it seems to just appear even without switching apps, but the lagginess always disappears once I quit LES

By laggy I don't mean input lag from MIDI, but really everything from hitting play to activating a track or moving midi notes on a grid or adjusting velocity
It's not a big lag, but just enough to be annoying, I'd say somewhere between 0.2 and 0.4 seconds maybe

I thought it might have to do with the loadspeed setting since it feels similar to the duration of the lag, but after changing said speed it doesn't seem to be the case

For controls mapped to a MIDI controller like Play/Stop, there doesn't seem to be any lag if I hit them using the controller, so maybe it's linked with the keyboard/mouse inputs specifically ?

I don't remember noticing any LES induced lag on Live prior to these MacOS / Ableton updates

Re installing LES did not fix the issue

**To Reproduce**
1. Go to Live
2. Click on another opened app window
3. Go back to Live

(Thanks for keeping this awesome tool alive)

**Comment by kwvg** [comment] 2023-07-29 09:31
Sorry for the late reply, I was trying to reproduce this locally with little to no luck. LES does hinge some of its functionality to fixed delays and I believed that perhaps tweaking that or allowing users to tweak it should remedy the problem but overall lag is something that I've been unable to reproduce.

Though LES does have pieces of logic that could cause itself to hang, I've not seen it cause disruption to other programs.

Could you enumerate a workflow that could help me reproduce the lagginess?

**Comment by OttoVonBorux** [comment] 2023-07-31 22:04
I thought the May 16 re-release was a response to this post since it seem to have solved the issue !
Now on Live 11.3.4 / Ventura 13.4.1 in the same conditions as before and I'm not noticing any more lag

If You're still curious on what caused the issue, I forgot to mention I'm using Magnet to manage the windows, since the problem usually appeared upon switching between windows maybe it could have to do with that ?

Thank You again for your efforts to keep LES stable

**Comment by kwvg** [comment] 2023-08-01 08:35
I'm glad the problem is resolved for you, I didn't think of asking about window managers and factoring their possible contributions to glitches and bugs, I use Tiles myself and have never had any problems.

I'll be closing this issue, do re-open it if the problem resurfaces.

**Closed as completed by kwvg** 2023-08-01 08:35 UTC
Labels: bug
