### ISSUE TITLE
'Accessibility access is disabled which prevents LES from working properly.'

### ISSUE THREAD

**Issue by davee23** [LiveEnhancementSuite/LESforMacOS#14] opened 2022-06-19 04:30 UTC
I have installed the latest LES MacOS version and I can't get past the following message:
'Accessibility access is disabled which prevents LES from working properly.
Please turn on accessibility access in
Preferences > Security & Privacy > Privacy > Accessibility, and try again.'

I've added tried removing and adding LES in the Accessibility list without any luck. 

I'm on MacOS Monterey v 12.4 (21F79).

Are there any work arounds?

**Comment by ciuchka2222** [comment] 2022-06-25 10:41
Same on an M1. 12.4 Would so love to use this :(

**Comment by Cevah3ro** [comment] 2022-06-26 23:17
Same on M1 Max 12.4

**Comment by Inversil** [comment] 2022-06-28 15:51
This is a duplicate of issue https://github.com/LiveEnhancementSuite/LESforMacOS/issues/6
let me know if the solution at the bottom of that page does anything for you

**Closed as completed by Inversil** 2022-06-28 15:51 UTC
