### ISSUE TITLE
[Bug] Accessibility access can not be enabled on MacOs 13.2.1 . the issue still . It's like don't recognize the change has been applied already . Please Help ! that does not happen in the previous version (0.9.78)

### ISSUE THREAD

**Issue by DanyEasy** [LiveEnhancementSuite/LESforMacOS#21] opened 2023-03-06 22:40 UTC
Accessibility access can not be enabled on MacOs 13.2.1 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/127155585/223264557-b2b040cb-3c45-4daa-9afd-296760d57e23.png">

<img width="490" alt="image" src="https://user-images.githubusercontent.com/127155585/223265493-7ebc43a4-73a2-4ff1-a133-245ebab81703.png">

And the issue still . It's like don't recognize the change has been applied already . Please Help !
that does not happen in the previous version (0.9.78)

**Comment by ghost** [comment] 2023-03-07 17:34
I am also experiencing the same issue after adding live and handsome and sweet to accessibility

**Comment by mitchscullin** [comment] 2023-03-09 12:55
I've just tried today as well, MacOS 13.2.1 and it isn't recognising the accessibility access :(

**Comment by ChasonDeshotel** [comment] 2023-03-11 09:43
I had this issue on 10.14.6 and was able to resolve it by toggling the permission off and back on

**Comment by mitchscullin** [comment] 2023-03-11 09:53
I've tried this it doesn't do anything still comes up with this prompt.
<img width="426" alt="Screenshot 2023-03-11 at 09 53 03" src="https://user-images.githubusercontent.com/127409215/224477614-b311550b-ba88-4ce3-ad5d-0a04029fcb68.png">

**Comment by zarakershaw** [comment] 2023-03-12 09:49
This is also happening for me :( damn

**Comment by Jailbot07** [comment] 2023-04-25 15:57
Same here

**Comment by kwvg** [comment] 2023-05-21 20:17
Duplicate of https://github.com/LiveEnhancementSuite/LESforMacOS/issues/6

**Closed as not planned by kwvg** 2023-05-21 20:17 UTC
Labels: bug, duplicate
