### ISSUE TITLE
Accessibility Error is in error

### ISSUE THREAD

**Issue by soundsliketree** [LiveEnhancementSuite/LESforMacOS#18] opened 2023-01-05 08:32 UTC
**Describe the bug**
Upon trying to Open LES I receive an error that LES is not enabled in preferences, but it is.

**Screenshots**
Please see attached files.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 
 - Version 12.4

**Additional context**
![Screen Shot 2023-01-05 at 12 28 33 AM](https://user-images.githubusercontent.com/122010066/210735665-9d5ffe23-7409-4ef6-a568-571d2d90cc72.png)
<img width="487" alt="Screen Shot 2023-01-05 at 12 29 01 AM" src="https://user-images.githubusercontent.com/122010066/210735670-5cfc9b72-8aa0-4870-90bb-1b00e0056fed.png">
<img width="556" alt="Screen Shot 2023-01-05 at 12 28 47 AM" src="https://user-images.githubusercontent.com/122010066/210735673-3dde1005-b8b2-4ec2-b104-ebbe0a318bea.png">

**Comment by daikizen** [comment] 2023-01-08 03:30
I've the same problem....

**Comment by alexandrefaivre05** [comment] 2023-01-16 20:39
same :(

**Comment by vontaylor** [comment] 2023-01-17 21:18
*** found this online now it works

Seems to be working fine with a small workaround. If you try to open it like normal it will ask you to enable certain permissions, even if you’ve already enabled them. Instead of opening LES like normal, right click it and choose ‘show package contents’. Then open the item called ‘hammerspoon’. This will allow it to work for some reason. Make a shortcut for ‘hammerspoon’ on your desktop and open this anytime you need to open Live Enhancement Suite.

**Comment by Banjaman** [comment] 2023-02-15 10:02
> *** found this online now it works
> 
> Seems to be working fine with a small workaround. If you try to open it like normal it will ask you to enable certain permissions, even if you’ve already enabled them. Instead of opening LES like normal, right click it and choose ‘show package contents’. Then open the item called ‘hammerspoon’. This will allow it to work for some reason. Make a shortcut for ‘hammerspoon’ on your desktop and open this anytime you need to open Live Enhancement Suite.

This didn't worked out for me, still the same windows pops up that Accessibility ist not enabled but it is. Can you share a screenshot of the "hammer spoon" folder?

**Comment by axldarealest** [comment] 2023-02-17 01:24
you have to autorize terminal too in accessibility

**Comment by dxugy** [comment] 2023-02-23 16:58
still haven't been able to get around this

**Comment by ignacio-dev** [comment] 2023-02-24 11:09
Same issue here :(

**Comment by ignacio-dev** [comment] 2023-02-24 11:38
I managed to open Hammerspoon using:
```
sudo /Applications/Live\ Enhancement\ Suite.app/Contents/MacOS/Hammerspoon
```
(and then typing my password)
The icon appears on top of the screen as expected. However, it has no effect on Ableton... none of my menus show up.

**Comment by emeren** [comment] 2023-03-13 15:13
Same issue with privacy settings :(

**Comment by kwvg** [comment] 2023-05-21 20:14
Duplicate of https://github.com/LiveEnhancementSuite/LESforMacOS/issues/6

**Closed as not planned by kwvg** 2023-05-21 20:14 UTC
Labels: bug, duplicate
